---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "web-app"
  namespace: "node-app"
  labels:
    app: "web-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "web-app"
  template:
    metadata:
      labels:
        app: "web-app"
    spec:
      containers:
        - name: "web-server"
          image: "cherkkss/node-app"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
          - name: HOST
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: host
          - name: PASS
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
          - name: USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: username